(cl:in-package coman_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          XFORCENEWTONS-VAL
          XFORCENEWTONS
          YFORCENEWTONS-VAL
          YFORCENEWTONS
          ZFORCENEWTONS-VAL
          ZFORCENEWTONS
          XTORQUENEWTONMETERS-VAL
          XTORQUENEWTONMETERS
          YTORQUENEWTONMETERS-VAL
          YTORQUENEWTONMETERS
          ZTORQUENEWTONMETERS-VAL
          ZTORQUENEWTONMETERS
))