controller_list:
  - name: fake_right_arm_controller
    joints:
      - RShSag
      - RShLat
      - RShYaw
      - RElbj
      - RForearmPlate
      - RWrj1
      - RWrj2
  - name: fake_left_arm_controller
    joints:
      - LShSag
      - LShLat
      - LShYaw
      - LElbj
      - LForearmPlate
      - LWrj1
      - LWrj2
  - name: fake_right_leg_controller
    joints:
      - RHipSag
      - RHipLat
      - RHipYaw
      - RKneeSag
      - RAnkLat
      - RAnkSag
  - name: fake_left_leg_controller
    joints:
      - LHipSag
      - LHipLat
      - LHipYaw
      - LKneeSag
      - LAnkLat
      - LAnkSag