controller_list:
  - name: fake_right_arm_controller
    joints:
      - RShSag
      - RShLat
      - RShYaw
      - RElbj
      - RForearmPlate
      - RWrj1
      - RWrj2
  - name: fake_left_arm_controller
    joints:
      - LShSag
      - LShLat
      - LShYaw
      - LElbj
      - LForearmPlate
      - LWrj1
      - LWrj2