/* Auto-generated by genmsg_cpp for file /home/enrico/ros_workspace/iit-coman-ros-pkg/coman_msgs/msg/ForceTorque.msg */
#ifndef COMAN_MSGS_MESSAGE_FORCETORQUE_H
#define COMAN_MSGS_MESSAGE_FORCETORQUE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace coman_msgs
{
template <class ContainerAllocator>
struct ForceTorque_ {
  typedef ForceTorque_<ContainerAllocator> Type;

  ForceTorque_()
  : header()
  , xForceNewtons(0.0)
  , yForceNewtons(0.0)
  , zForceNewtons(0.0)
  , xTorqueNewtonMeters(0.0)
  , yTorqueNewtonMeters(0.0)
  , zTorqueNewtonMeters(0.0)
  {
  }

  ForceTorque_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , xForceNewtons(0.0)
  , yForceNewtons(0.0)
  , zForceNewtons(0.0)
  , xTorqueNewtonMeters(0.0)
  , yTorqueNewtonMeters(0.0)
  , zTorqueNewtonMeters(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _xForceNewtons_type;
  double xForceNewtons;

  typedef double _yForceNewtons_type;
  double yForceNewtons;

  typedef double _zForceNewtons_type;
  double zForceNewtons;

  typedef double _xTorqueNewtonMeters_type;
  double xTorqueNewtonMeters;

  typedef double _yTorqueNewtonMeters_type;
  double yTorqueNewtonMeters;

  typedef double _zTorqueNewtonMeters_type;
  double zTorqueNewtonMeters;


  typedef boost::shared_ptr< ::coman_msgs::ForceTorque_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coman_msgs::ForceTorque_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ForceTorque
typedef  ::coman_msgs::ForceTorque_<std::allocator<void> > ForceTorque;

typedef boost::shared_ptr< ::coman_msgs::ForceTorque> ForceTorquePtr;
typedef boost::shared_ptr< ::coman_msgs::ForceTorque const> ForceTorqueConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::coman_msgs::ForceTorque_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::coman_msgs::ForceTorque_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace coman_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::coman_msgs::ForceTorque_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::coman_msgs::ForceTorque_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::coman_msgs::ForceTorque_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b34fdd2e02f35ff10dc9a8e2137fa7ea";
  }

  static const char* value(const  ::coman_msgs::ForceTorque_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb34fdd2e02f35ff1ULL;
  static const uint64_t static_value2 = 0x0dc9a8e2137fa7eaULL;
};

template<class ContainerAllocator>
struct DataType< ::coman_msgs::ForceTorque_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coman_msgs/ForceTorque";
  }

  static const char* value(const  ::coman_msgs::ForceTorque_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coman_msgs::ForceTorque_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float64 xForceNewtons\n\
float64 yForceNewtons\n\
float64 zForceNewtons\n\
float64 xTorqueNewtonMeters\n\
float64 yTorqueNewtonMeters\n\
float64 zTorqueNewtonMeters\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::coman_msgs::ForceTorque_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::coman_msgs::ForceTorque_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::coman_msgs::ForceTorque_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coman_msgs::ForceTorque_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.xForceNewtons);
    stream.next(m.yForceNewtons);
    stream.next(m.zForceNewtons);
    stream.next(m.xTorqueNewtonMeters);
    stream.next(m.yTorqueNewtonMeters);
    stream.next(m.zTorqueNewtonMeters);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ForceTorque_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coman_msgs::ForceTorque_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::coman_msgs::ForceTorque_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xForceNewtons: ";
    Printer<double>::stream(s, indent + "  ", v.xForceNewtons);
    s << indent << "yForceNewtons: ";
    Printer<double>::stream(s, indent + "  ", v.yForceNewtons);
    s << indent << "zForceNewtons: ";
    Printer<double>::stream(s, indent + "  ", v.zForceNewtons);
    s << indent << "xTorqueNewtonMeters: ";
    Printer<double>::stream(s, indent + "  ", v.xTorqueNewtonMeters);
    s << indent << "yTorqueNewtonMeters: ";
    Printer<double>::stream(s, indent + "  ", v.yTorqueNewtonMeters);
    s << indent << "zTorqueNewtonMeters: ";
    Printer<double>::stream(s, indent + "  ", v.zTorqueNewtonMeters);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMAN_MSGS_MESSAGE_FORCETORQUE_H

