/* Auto-generated by genmsg_cpp for file /home/enrico/ros_workspace/iit-coman-ros-pkg/coman_msgs/msg/JointExtraInformation.msg */
#ifndef COMAN_MSGS_MESSAGE_JOINTEXTRAINFORMATION_H
#define COMAN_MSGS_MESSAGE_JOINTEXTRAINFORMATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace coman_msgs
{
template <class ContainerAllocator>
struct JointExtraInformation_ {
  typedef JointExtraInformation_<ContainerAllocator> Type;

  JointExtraInformation_()
  : header()
  , name()
  , Current()
  {
  }

  JointExtraInformation_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , name(_alloc)
  , Current(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  name;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _Current_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  Current;


  typedef boost::shared_ptr< ::coman_msgs::JointExtraInformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coman_msgs::JointExtraInformation_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointExtraInformation
typedef  ::coman_msgs::JointExtraInformation_<std::allocator<void> > JointExtraInformation;

typedef boost::shared_ptr< ::coman_msgs::JointExtraInformation> JointExtraInformationPtr;
typedef boost::shared_ptr< ::coman_msgs::JointExtraInformation const> JointExtraInformationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::coman_msgs::JointExtraInformation_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::coman_msgs::JointExtraInformation_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace coman_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::coman_msgs::JointExtraInformation_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::coman_msgs::JointExtraInformation_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::coman_msgs::JointExtraInformation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1140fd749aaf24e9b18248b113ed48c0";
  }

  static const char* value(const  ::coman_msgs::JointExtraInformation_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1140fd749aaf24e9ULL;
  static const uint64_t static_value2 = 0xb18248b113ed48c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::coman_msgs::JointExtraInformation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coman_msgs/JointExtraInformation";
  }

  static const char* value(const  ::coman_msgs::JointExtraInformation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coman_msgs::JointExtraInformation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
string[] name\n\
float64[] Current  \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::coman_msgs::JointExtraInformation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::coman_msgs::JointExtraInformation_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::coman_msgs::JointExtraInformation_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coman_msgs::JointExtraInformation_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.name);
    stream.next(m.Current);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointExtraInformation_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coman_msgs::JointExtraInformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::coman_msgs::JointExtraInformation_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "Current[]" << std::endl;
    for (size_t i = 0; i < v.Current.size(); ++i)
    {
      s << indent << "  Current[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.Current[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMAN_MSGS_MESSAGE_JOINTEXTRAINFORMATION_H

