/* Auto-generated by genmsg_cpp for file /home/enrico/ros_workspace/iit-coman-ros-pkg/coman_msgs/msg/PID.msg */
#ifndef COMAN_MSGS_MESSAGE_PID_H
#define COMAN_MSGS_MESSAGE_PID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace coman_msgs
{
template <class ContainerAllocator>
struct PID_ {
  typedef PID_<ContainerAllocator> Type;

  PID_()
  : header()
  , name()
  , P()
  , I()
  , D()
  {
  }

  PID_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , name(_alloc)
  , P(_alloc)
  , I(_alloc)
  , D(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  name;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _P_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  P;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _I_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  I;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _D_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  D;


  typedef boost::shared_ptr< ::coman_msgs::PID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coman_msgs::PID_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PID
typedef  ::coman_msgs::PID_<std::allocator<void> > PID;

typedef boost::shared_ptr< ::coman_msgs::PID> PIDPtr;
typedef boost::shared_ptr< ::coman_msgs::PID const> PIDConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::coman_msgs::PID_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::coman_msgs::PID_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace coman_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::coman_msgs::PID_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::coman_msgs::PID_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::coman_msgs::PID_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff8be1f9b7b2878c3666b8df1c84ba9d";
  }

  static const char* value(const  ::coman_msgs::PID_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff8be1f9b7b2878cULL;
  static const uint64_t static_value2 = 0x3666b8df1c84ba9dULL;
};

template<class ContainerAllocator>
struct DataType< ::coman_msgs::PID_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coman_msgs/PID";
  }

  static const char* value(const  ::coman_msgs::PID_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coman_msgs::PID_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
string[] name\n\
float64[] P # if joint impedance control this has to be Nm/rad \n\
float64[] I\n\
float64[] D\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::coman_msgs::PID_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::coman_msgs::PID_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::coman_msgs::PID_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coman_msgs::PID_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.name);
    stream.next(m.P);
    stream.next(m.I);
    stream.next(m.D);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PID_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coman_msgs::PID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::coman_msgs::PID_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "P[]" << std::endl;
    for (size_t i = 0; i < v.P.size(); ++i)
    {
      s << indent << "  P[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.P[i]);
    }
    s << indent << "I[]" << std::endl;
    for (size_t i = 0; i < v.I.size(); ++i)
    {
      s << indent << "  I[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.I[i]);
    }
    s << indent << "D[]" << std::endl;
    for (size_t i = 0; i < v.D.size(); ++i)
    {
      s << indent << "  D[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.D[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMAN_MSGS_MESSAGE_PID_H

